### ISSUE TITLE
.puml's do not actually show pictures

### ISSUE THREAD

**Issue by snelzing** [w-a-r-m-inventory-system/Food-Pantry-Inventory#35]
The .PUML's under DevDocs only shows text explanations of what happens with Git in PyCharm. From what I understand, they should be diagrams?

![puml](https://user-images.githubusercontent.com/39928924/55762041-6373b180-5a2f-11e9-8733-98fead0d93cf.PNG)

**Comment by snelzing** [comment]
![graphicalreps](https://user-images.githubusercontent.com/39928924/55762393-c154c900-5a30-11e9-8122-7b2f9149ac8c.PNG)

**Comment by deeppunster** [comment]
Yes, after we talked, I realized that they are in the other "Christmas Label" repository and that they only show  the diagrams if you build the Sphinx documentation.  I have since saved the diagrams  in  the repository at

https://github.com/deeppunster/Christmas-Labels/blob/master/docs/source/UML/Git%20Update%20from%20Main%20Use%20Case.png

and

https://github.com/deeppunster/Christmas-Labels/blob/master/docs/source/UML/Git%20Update%20from%20Main%20Sequence.png

for your convenience.

**Comment by deeppunster** [comment]
BTW, the .puml files will show diagrams if one has PlantUML installed and configured.  It does need for one to click on the PlantUML tab on the right (or choose View -> Tool Windows -> PlantUML from  the menu).

**Comment by snelzing** [comment]
There is not actually anything to render PlantUML in Github, it will render if brought up in PyCharm.
