### ISSUE TITLE
Getting error from autodoc when running Sphinx to create documentation

### ISSUE THREAD

**Issue by deeppunster** [w-a-r-m-inventory-system/Food-Pantry-Inventory#58]
Getting following error and traceback:

**WARNING: autodoc: failed to import module 'views' from module 'fpiweb'; the following exception was raised:**

> Traceback (most recent call last):
>   File "/Volumes/MBPC/Dvl/Python/PythonProjects/Food-Pantry-Inventory/venv/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 232, in import_module
>     __import__(modname)
>   File "/Volumes/MBPC/Dvl/Python/PythonProjects/Food-Pantry-Inventory/fpiweb/views.py", line 6, in <module>
>     from django.contrib.auth.mixins import LoginRequiredMixin
>   File "/Volumes/MBPC/Dvl/Python/PythonProjects/Food-Pantry-Inventory/venv/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 3, in <module>
>     from django.contrib.auth.views import redirect_to_login
>   File "/Volumes/MBPC/Dvl/Python/PythonProjects/Food-Pantry-Inventory/venv/lib/python3.7/site-packages/django/contrib/auth/views.py", line 10, in <module>
>     from django.contrib.auth.forms import (
>   File "/Volumes/MBPC/Dvl/Python/PythonProjects/Food-Pantry-Inventory/venv/lib/python3.7/site-packages/django/contrib/auth/forms.py", line 10, in <module>
>     from django.contrib.auth.models import User
>   File "/Volumes/MBPC/Dvl/Python/PythonProjects/Food-Pantry-Inventory/venv/lib/python3.7/site-packages/django/contrib/auth/models.py", line 3, in <module>
>     from django.contrib.contenttypes.models import ContentType
>   File "/Volumes/MBPC/Dvl/Python/PythonProjects/Food-Pantry-Inventory/venv/lib/python3.7/site-packages/django/contrib/contenttypes/models.py", line 133, in <module>
>     class ContentType(models.Model):
>   File "/Volumes/MBPC/Dvl/Python/PythonProjects/Food-Pantry-Inventory/venv/lib/python3.7/site-packages/django/db/models/base.py", line 111, in __new__
>     "INSTALLED_APPS." % (module, name)
> 

**RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.**

**Comment by jocassid** [comment]
Please add bug label

**Comment by jallman112** [comment]
I'm taking a look and this, and am making some progress.  Want to assign it to me?

**Comment by jallman112** [comment]
I've gotten rid of the RuntimeErrors and reduced the warnings by removing duplicate references.

I'm now down to these two warnings:
`/docs/source/JavaScriptAndJQuery.rst: WARNING: document isn't included in any toctree`
`/docs/source/modules.rst: WARNING: document isn't included in any toctree`

And several cases of:
`WARNING: plantuml command 'plantuml' cannot be run`
I'm assuming this one is because I don't have `plantuml` installed locally.

Finally there's this warning, which is still baffling me at the moment:
`/StandaloneTools/QRCodePrinter.py:docstring of StandaloneTools.QRCodePrinter:13: WARNING: Option list ends without a blank line; unexpected unindent.`

**Comment by jallman112** [comment]
@deeppunster found a couple missing commas that resolved the unexpected indent warning.

After installing plantuml those errors went away

**Comment by deeppunster** [comment]
Yes, I will close this issue.  If it crops up again, we can open a new issue.
